### ISSUE TITLE
Did you consider canvas.captureStream and MediaStreamTrackProcessor?

### ISSUE THREAD

**Issue by dalecurtis** [hughfenghen/wcm-recoder#1]
Thanks for the nice sample!

Did you consider using `canvas.captureStream()` and `MediaStreamTrackProcessor` to produce a ReadableStream you can transfer to the worker? You don't have to manually `createImageBitmap()` from the canvas and transfer then.

https://github.com/w3c/webcodecs/tree/main/samples/capture-to-file shows how to do this with camera capture.

**Comment by hughfenghen** [comment]
@dalecurtis  Can you tell me the background of the problem?
I don't see the benefit of using canvas.captureStream() and MediaStreamTrackProcessor instead of ImageBitmap.

**Comment by dalecurtis** [comment]
Instead of having to create and transfer each individual frame you just transfer the stream once and receive video frames directly in the worker. In some cases `captureStream` may be able to optimize readback by using GpuMemoryBuffers to improve hardware encoding performance.

I expect it may not show too much improvement in a simple application, but for busy main threads it's less work in JS. It should be less code overall too. 

Up to you in any case, just wanted to point it out if you hadn't seen it.

**Comment by hughfenghen** [comment]
@dalecurtis 
Thanks, this is very nice advice.

Just one small question, if I want to drop frames (network or CPU busy), can I only set a higher frameRate (`captureStream(60) or captureStream(90)`) and then drop the VideoFrame from MediaStreamTrackProcessor.readable?

Is a higher frameRate value possible to waste resources?

**Comment by dalecurtis** [comment]
You probably don't want to set frameRate since that will causes frames to only be generated when the canvas changes:

> If not set, a new frame will be captured each time the canvas changes

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream

It will cause higher CPU usage to generate synthetic frames, so I wouldn't set a frameRate unless you need to for some reason.

**Comment by hughfenghen** [comment]
Ok, i will try to use MediaStreamTrackProcessor.readable instead of ImageBitmap.
